SELECT  TOP (100)
        '[KinnserBIBaseData]' AS [0]
        ,[index]
        ,[PatientKey]       -- grain
        ,[LastName]
        ,[FirstName]
        ,[MiddleInitial]
        ,[ResidenceType]
        ,[MedicalRecordNum]
        ,[MedicaidNum]
        ,[DateofBirth]
        ,[Gender]
        ,[Address]
        ,[City]
        ,[County]
        ,[State]
        ,[ZipCode]
        ,[Phone]
        ,[AdmissionKey]     -- grain
        ,[AdmissionDate]
        ,[DischargeDate]
        ,[AdmissionYear]
        ,[DischargeYear]
        ,[EpisodeKey]       -- grain
        ,[InsuranceName]
        ,[InsuranceType]
        ,[InsuranceKey]
        ,[EpisodeStartDate]
        ,[EpisodeEndDate]
        ,[ICD10PrimaryDiagnosisCode]
        ,[ICD10PrimaryDiagnosisDescription]
        ,[ICD10SecondaryDiagnosisCode]
        ,[ICD10SecondaryDiagnosisDescription]
        ,[ICD10PrimaryDiagnosis]
        ,[ICD10SecondaryDiagnosis]
        ,[ICDVersion]
        ,[PrimaryDx]
        ,[SecondaryDx_A]
        ,[SecondaryDx_B]
        ,[SecondaryDx_C]
        ,[SecondaryDx_D]
        ,[SecondaryDx_E]
        ,[SecondaryDx_F]
        ,[SecondaryDx_G]
        ,[SecondaryDx_H]
        ,[SecondaryDx_I]
        ,[SecondaryDx_J]
        ,[SecondaryDx_K]
        ,[SecondaryDx_L]
        ,[SecondaryDx_M]
        ,[SecondaryDx_N]
        ,[SecondaryDx_O]
        ,[SecondaryDx_P]
        ,[SecondaryDx_Q]
        ,[ClinicKey]
        ,[BranchKey]
        ,[CorporationKey]
        ,[CorporationName]
        ,[ClinicName]
        ,[ClinicShortName]
        ,[BranchName]
        ,[BranchShortName]
        ,[ClinicAddress]
        ,[ClinicCity]
        ,[ClinicState]
        ,[ClinicalGroup]
FROM    [ScratchDB].[dbo].[KinnserBIBaseData]
ORDER BY [PatientKey];

SELECT  TOP (100) 
        '[KinnserCrosswalk]' AS [1]
        ,[index]
        ,[PatientKey]
        ,[icd10_level]
        ,[ICD10CODE]
        ,[ICD10CODE_LEN]
        ,[ICD_3Char]
        ,[ICD_4Char]
        ,[ICD_5Char]
        ,[row_id]
        ,[cc_category]
FROM    [ScratchDB].[dbo].[KinnserCrosswalk]
ORDER BY [PatientKey];

SELECT  TOP (100) 
        '[KinnserPatientScore]' AS [2]
        ,[level_0]
        ,[index]
        ,[PatientKey]
        ,[hcc_ce]
        ,[hcc_ins]
        ,[hcc_ne]
        ,[hcc_cc_ce]
        ,[hcupModelScore]
        ,[lr_cc]
        ,[rf_cc]
        ,[num_cc]
        ,[cc_readmission]
        ,[patient_risk_score]
        ,[patient_risk_score_scale]
        ,[RiskStratify]
FROM    [ScratchDB].[dbo].[KinnserPatientScore]
ORDER BY [PatientKey];