SELECT  TOP (1000) 
        '[LTC400BaseData]' AS [0]
        ,[index]
        ,[PharmacyCode],[Resident]  -- PatientKey
        ,[FirstName]
        ,[MiddleInitial]
        ,[LastName]
        ,[SexCode]
        ,[FinPlan]
        ,[PrivateInsurance2]
        ,[Medicaidfinancial]
        ,[Facility]
        ,[Status]
        ,[AdmitDate]                -- Grain
        ,[DischargeDate]            -- Grain
        ,[Birthdate]
        ,[MedicareNbr]
        ,[MedicaidNbr]
        ,[Address1]
        ,[Address2]
        ,[City]
        ,[State]
        ,[ZipCode]
        ,[ZipCodePlus4]
        ,[HomePhone]
        ,[WorkPhone]
        ,[EMailID]
        ,[FacilityName]
        ,[FacilityAddress1]
        ,[FacilityAddress2]
        ,[FacilityCity]
        ,[FacilityState]
        ,[FacilityZip]
        ,[FacilityPhone]
        ,[ICD10CODE]                -- Grain
FROM    [ScratchDB].[dbo].[LTC400BaseData]
ORDER BY [PharmacyCode], [Resident];

SELECT  TOP (1000) 
        '[LTC400Crosswalk]' AS [1]
        ,[index]
        ,[PatientKey]
        ,[icd10_level]
        ,[ICD10CODE]
        ,[ICD10CODE_LEN]
        ,[ICD_3Char]
        ,[ICD_4Char]
        ,[ICD_5Char]
        ,[row_id]
        ,[cc_category]
FROM    [ScratchDB].[dbo].[LTC400Crosswalk]
ORDER BY [PatientKey];

SELECT  TOP (1000) 
        '[LTC400PatientScore]' AS [2]
        ,[level_0]
        ,[index]
        ,[PatientKey]
        ,[hcc_ce]
        ,[hcc_ins]
        ,[hcc_ne]
        ,[hcc_cc_ce]
        ,[hcupModelScore]
        ,[lr_cc]
        ,[rf_cc]
        ,[num_cc]
        ,[cc_readmission]
        ,[patient_risk_score]
        ,[patient_risk_score_scale]
        ,[RiskStratify]
FROM    [ScratchDB].[dbo].[LTC400PatientScore]
ORDER BY [PatientKey];