FROM ubuntu:18.04

# Set Locale - required for ODBC driver
RUN apt-get update \
    && apt-get install -y \
        locales \
    && apt-get update \
    && sed -i -e 's/# en_US.UTF-8 UTF-8/en_US.UTF-8 UTF-8/' /etc/locale.gen \
    && locale-gen

ENV ACCEPT_EULA=Y
ENV LANG en_US.UTF-8
ENV LANGUAGE en_US:en
ENV LC_ALL en_US.UTF-8

# Download appropriate package for the OS version
#curl https://packages.microsoft.com/config/ubuntu/[##.##]/prod.list > /etc/apt/sources.list.d/mssql-release.list
RUN apt-get update \
    && apt-get install -y \
        curl \
        software-properties-common \
    && apt-get update \
    && curl https://packages.microsoft.com/keys/microsoft.asc | apt-key add - \
    && curl https://packages.microsoft.com/config/ubuntu/18.04/prod.list > /etc/apt/sources.list.d/mssql-release.list \
    && apt-get update \
    && apt-get install -y \
        msodbcsql17 \
        mssql-tools \
        unixodbc-dev \
        python3-pip \
    && apt-get update \
    && rm -rf /var/lib/apt/lists/*

# optional: for bcp and sqlcmd
ENV PATH="$PATH:/opt/mssql-tools/bin"
ENV WORK_HOME /opt/pandas-service

COPY requirements.txt ${WORK_HOME}/requirements.txt

RUN buildDeps='build-essential git' \
    && set -x \
    && apt-get update \
    && apt-get install -y $buildDeps \
    && apt-get update \
    && pip3 install --upgrade pip==9.0.3 \
    && pip3 install -r ${WORK_HOME}/requirements.txt \
    && rm -rf /var/lib/apt/lists/* 
    #&& apt-get purge -y --auto-remove $buildDeps

COPY ./pandas_methods ${WORK_HOME}/pandas_methods
COPY ./main.py ${WORK_HOME}

WORKDIR ${WORK_HOME}
ENV PATH=$PATH:${WORK_HOME}
ENV PYTHONPATH ${WORK_HOME}

#CMD ["python3.6", "main.py"]